Add support to the multiple file format support feature.
KarypisLab/ParMETIS pull request #14
Opened 2022-05-25 18:52 UTC by kylasa

This Pull Request is part of the Distributed Graph Partitioning feature pipeline to support massively large graphs for distributed training. This is to add support to the ParMETIS to read input graph files which are in multiple file format. Here it is assumed that each process is mapped to a input graph file for each of the graph files (nodes, edges, node features and edge features). Each process reads nodes/edges file which is assigned to the current process, using the process-id as suffix string to the appropriate input graph file name. After reading the input graph file, we as

2022-09-07 09:15 UTC, Rhett-Ying commented on programs/dglpart2.c
>      nchunks = 1+gnedges/chunksize;
if `gnedges%chunksize == 0`, does `+1` work as expected? same issue for below `edgecount`.

2022-09-09 08:51 UTC, Rhett-Ying requested changes

2022-09-09 08:51 UTC, Rhett-Ying commented on programs/CMakeLists.txt
> +add_executable(pm_dglpart3 dglpart3.c)
where's `dglpart3.c`? the below file should be renamed?

2022-09-09 08:51 UTC, Rhett-Ying commented on programs/dglpart2.c
> +      printf("Usage: %s <fstem> <nparts> <nodes_file> <edges_file>\n", argv[0]);
after reviewing https://github.com/dmlc/dgl/pull/4529, the original `xxx_nodes.txt` and `xxx_edges.txt` have been replaced by `nodes_file` and `edges_files` which includes the all `xxx_nodes/edges.txt` file path. right? If yes, do we need 5 arguments here?

2022-09-09 08:51 UTC, Rhett-Ying commented on programs/dglpart2.c
> +  //sprintf(filename, "%s_nodes_%02d.txt", fstem, mype);
I think the content(namely the real path of `xxx_nodes/edges.txt`) in these 2 files should be checked here.

2022-09-26 10:09 UTC, kylasa commented on programs/CMakeLists.txt
> +add_executable(pm_dglpart3 dglpart3.c)
That is the convension which is being followed in this code base. I guess this is something which we cannot change right now.

2022-09-26 10:13 UTC, kylasa commented on programs/dglpart2.c
> +      printf("Usage: %s <fstem> <nparts> <nodes_file> <edges_file>\n", argv[0]);
No. I think there is some mis-understanding here. I added only two arguments `nfiles` and `efiles` paramters to the existing command. So I guess we only need 4 parameters.

2022-09-26 10:14 UTC, kylasa commented on programs/dglpart2.c
> +      printf("Usage: %s <fstem> <nparts> <nodes_file> <edges_file>\n", argv[0]);
About ReadME and example usage, please propose a place where this sample usage command can be placed. But I believe our dgl.doc.ai documentation should have enough documentation about the way we plan to use ParMETIS.

2022-09-26 10:20 UTC, kylasa commented on programs/CMakeLists.txt
> +add_executable(pm_dglpart3 dglpart3.c)
dglpart3.c exits in the `programs' folder of the ParMETIS installation.

2022-09-26 10:32 UTC, kylasa commented on programs/dglpart2.c
> +  //sprintf(filename, "%s_nodes_%02d.txt", fstem, mype);
Done.

2023-03-26 19:14 UTC, merged